# Generated by Django 3.1.3 on 2022-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20221004_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gradePoint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionContent',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
