# Generated by Django 3.1.3 on 2022-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20221004_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Content',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
